import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#C7EBF9",
    padding: 10,
  },
  containerScroll: {
    flexGrow: 1,
    backgroundColor: "#C7EBF9",
    padding: 20,
    justifyContent: "space-between",
  },
  text: {
    fontSize: 18,
    fontFamily: "RobotoRegular",
    marginBottom: 20,
    textAlign: "justify",
  },
  logo: {
    width: "100%",
    height: "25%",
    marginBottom: 20,
    borderRadius: 7,
  },
  heading: {
    fontSize: 30,
    fontWeight: "bold",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    marginBottom: 10,
  },
  homePicture: {
    width: "100%",
    height: 386,
    alignItems: "center",
    justifyContent: "center",
  },
  button: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: "#2D5DA4",
    marginTop: 15,
  },
  redButton:{
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: "red",
    marginTop: 15,
  },
  textBtn: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "white",
    paddingLeft: 5,
  },
  messageText: {
    fontSize: 16,
    color: "black",
    width: "55%",
  },
  sendBtn: {
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    backgroundColor: "#2D5DA4",
    padding: 8,
  },
  avatarStyle: {
    width: 60,
    height: 60,
    borderColor: "black",
    justifyContent: "center",
    alignContent: "center",
    backgroundColor: "#C7EBF9",
    margin: 10,
  },
  avatarStyleCurrentUser: {
    width: 50,
    height: 50,
    borderColor: "black",
    justifyContent: "center",
    alignContent: "flex-start",
    backgroundColor: "#C7EBF9",
    margin: 5,
  },
  avatarStyleCurrentChat: {
    width: 50,
    height: 50,
    borderColor: "black",
    justifyContent: "end",
    alignContent: "end",
    backgroundColor: "#C7EBF9",
    margin: 5,
  },
  userProfileAvatar: {
    width: "100%",
    height: "30%",
    alignItems: "center",
    marginBottom: 40,
  },
  userProfileTextContainer:{
    flexDirection: "row",
    padding: 10,
    justifyContent: "space-between",
  },
  userProfileInputContainer:{
    flexDirection:'column'
  },
  avatarProfile: {
    width: 120,
    height: 120,
    borderColor: "black",
    justifyContent: "center",
    alignContent: "center",
    backgroundColor: "#C7EBF9",
    margin: 10,
  },
  emojiBtn: {
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    padding: 8,
    paddingRight: 12,
    justifyContent: "center",
  },
  inputMsg: {
    flexDirection: "row",
    borderWidth: 1,
    borderTopLeftRadius: 7,
    borderTopEndRadius: 7,
    borderColor: "#777",
    alignItems: "center",
    justifyContent: "space-between",
  },
  input: {
    borderWidth: 1,
    borderRadius: 7,
    borderColor: "#777",
    padding: 8,
    marginTop: 10,
    marginBottom: 10,
  },
  userChatButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    alignContent: "center",
    padding: 5,
  },
  textUserChatBtn: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "black",
    marginRight: 10,
    marginLeft: 10,
    marginTop: 6,
  },
  avatarContainer: {
    width: 50,
    height: 50,
  },
  avatar: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  chatScreenName: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: 7,
    marginBottom: 7,
    border: 1,
    borderRadius: 4,
  },
  inputContainer: {
    flex: 1,
    justifyContent: "space-around",
    backgroundColor: "#C7EBF9",
  },
  messageChipFromMe: {
    borderWidth: 1,
    borderRadius: 16,
    borderBottomRightRadius: 0,
    borderColor: "#777",
    padding: 10,
    margin: 10,
    backgroundColor: "#C3D5EA",
    justifyContent: "center",
    marginLeft: 7,
    marginRight: 7,
    maxWidth: "max-content",
  },
  messageChipForMe: {
    borderRadius: 16,
    borderWidth: 1,
    borderBottomLeftRadius: 0,
    padding: 10,
    margin: 10,
    backgroundColor: "#4B8CE7",
    justifyContent: "center",
    alignContent:'center',
    marginRight: 7,
    marginLeft: 7,
    color: "white",
    maxWidth: "max-content",
  },
});
